apiVersion: v1
kind: Service
metadata:
  name: demo-spring-boot
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000 # Choisissez un port entre 30000 et 32767
  selector:
    app: demo-spring-boot